pre_bump_hooks = [
    "bash -c \"scripts/pre-bump.sh {{latest}} {{version}}\"",
]
post_bump_hooks = [
    "bash -c \"scripts/post-bump.sh {{latest}} {{version}} {{version+patch-SNAPSHOT}}\"",
]
pre_bump_hooks = [
    "nu -c \"cog-scripts/src/pre-bump.nu {{latest}} {{version}}\"",
]
post_bump_hooks = [
    "nu -c \"cog-scripts/src/post-bump.nu Minix {{latest}} {{version}} {{version+patch-SNAPSHOT}} -r -p [.,module-autoscanner,module-common,module-data,module-flowbus,module-integrations,module-jumper,module-ticker]\"",
]

tag_prefix = "v"

[commit_types]
gradle = { changelog_title = "Build" }
format = { changelog_title = "Formatting" }


[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


