pre_bump_hooks = [
    "sh -c \"echo '{{latest}}:{{version}} >> .temp'\"",
    "exit 1",
#    "sh -c \"scripts/pre-bump.sh",
]
post_bump_hooks = [
    "sh -c \"scripts/post-bump.sh {{latest}} {{version}}\"",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


