pre_bump_hooks = [
    "if ! ./gradlew test --info; then exit 1; fi",
    "echo 'Bumping from v{{latest}} to v{{version}}!'",
]
post_bump_hooks = [
    # Update the version in gradle properties and amend last commit
    "sed -i 's/version=.*/version={{version}}/' ./gradle.properties",
    "git add ./gradle.properties",
    "git commit --amend -C HEAD",
    # Push to github with new tag
    "git push",
    "git push origin v{{version}}",
    # Build gradle
    "./gradlew clean build -Pversion=\"{{version}}\"",
    # Create changelog and make new release
    "grep -Poz '(?s)(?<=## \\[v{{version}}]\\(https:\\/\\/github\\.com\\/DaRacci\\/Minix\\/compare\\/v{{latest}}.\\.v{{version}}) - ....-..-..\n).*?(?=- - -)' CHANGELOG.md >> ./.templog.md", # TODO: This is really fucking ugly
    "gh release create \"v{{version}}\" -F ./.templog.md -t 'Minix release {{version}}' build/libs/Minix-{{version}}.jar Minix-API/build/libs/Minix-API-{{version}}-sources.jar",
    "rm ./.templog.md",
    # Trigger the docs workflow
    "gh workflow run docs.yml",
    # Publish to repo
    "./gradlew :Minix-API:publish -Pversion=\"{{version}}\"",
    # Update tags
    "git fetch --tags origin",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


