pre_bump_hooks = [
    """
        sh -c "chmod u+x scripts/pre_bump.sh"
        sh -c "scripts/pre-bump.sh {{latest}} {{version}}"
    """,
]
post_bump_hooks = [
    """
        sh -c "chmod u+x scripts/post_bump.sh"
        sh -c "scripts/post-bump.sh {{latest}} {{version}}"
    """,
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


