pre_bump_hooks = [
    "sh -c \"echo '{{latest}}:{{version}} >> temp'\"",
]
post_bump_hooks = [
    "sh -c \"echo '{{latest}}:{{version}} >> temp'\"", # Create it again since we delete it in pre_bump_hooks so it doesnt stay if it fails
    "sh -c \"scripts/post-bump.sh {{latest}} {{version}}\"",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


