pre_bump_hooks = [
    "echo '{{latest}}:{{version}} >> temp'",
    "bash -c \"scripts/pre-bump.sh\"",
]
post_bump_hooks = [
    "echo '{{latest}}:{{version}} >> temp'", # Create it again since we delete it in pre_bump_hooks so it doesnt stay if it fails
    "bash -c \"scripts/post-bump.sh\"",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


