pre_bump_hooks = [
    """
        bash -c "if ! ./gradlew test --info; then exit 1; fi"
    """,
    "echo 'Bumping from {{latest}} to {{version}}!'",
]
post_bump_hooks = [
    # Update the version in gradle properties and amend last commit
    "sed -i 's/version=.*/version={{version}}/' ./gradle.properties",
    "git commit --amend",
    # Push to github with new tag
    "git push",
    "git push origin {{version}}",
    # Build gradle
    "./gradlew build -Pversion={{version}}",
    # Create changelog and make new release
    "cog changelog -a {{version}} -t default >> .templog.md",
    "gh release create {{version}} -F .templog.md -t 'Minix release {{version}}' builds/libs/Minix-{{version}}.jar Minix-API/builds/libs/Minix-API.jar Minix-API/builds/libs/Minix-API-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}-sources.jar Minix-Core/builds/libs/Minix-Core-{{version}}-sources.jar",
    "rm .templog.md",
    # Trigger the docs workflow
    "gh workflow run docs.yml",
    # Publish to repo
    "./gradlew publish -Pversion={{version}}",
    # Update tags
    "git fetch --tags origin",
    # Checkout and update the dev branch
    "git checkout dev",
    "git rebase master",
    # Update the version of the dev branch
    "sed -i \"s/version.*/version={{version+minor-SNAPSHOT}}/g\" ./gradle.properties",
    "git add gradle.properties",
    # Commit and push the dev branch
    "git commit -m 'Bump version to {{version+minor-SNAPSHOT}}'",
    "git push",
]

tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "Da_Racci"
authors = [
    { signature = "Racci", username = "Da_Racci" },
    { signature = "Da_Racci", username = "Da_Racci" }
]


