pre_bump_hooks = [
    "bash -c \"scripts/pre-bump.sh {{latest}} {{version}}\"",
]
post_bump_hooks = [
    "bash -c \"scripts/post-bump.sh {{latest}} {{version}}\"",
]

tag_prefix = "v"

[commit_types]
gradle = { changelog_title = "Build" }


[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "Minix"
owner = "DaRacci"
authors = [
    { signature = "Racci", username = "DaRacci" },
    { signature = "DaRacci", username = "DaRacci" }
]


