name: RacciCore
version: '${version}'
main: me.racci.raccicore.RacciCore
api-version: 1.17
load: STARTUP
loadbefore: [ Sylphia, Sylph, BloodNight, HollowsEve ]
authors: [ Racci ]
description: Core lib for my plugins
website: https://github.com/DaRacci/RacciCore/

libraries:
  - ${kotlin-stdlib}
  - ${kotlin-reflect}
  - ${kotlinX-coroutinesCore}
  - ${kotlinX-coroutinesJvm}
  - ${kotlinX-serializationJson}
  - ${kotlinX-dateTime}
  - ${commons-lang3}
  - ${commons-collections4}
  - ${commons-tex}
  - ${mcCoroutine-core}
  - ${mcCoroutine-API}
