name: RacciCore
version: '${version}'
main: me.racci.raccicore.RacciCore
api-version: 1.17
load: STARTUP
loadbefore: [ Sylphia, Sylph, BloodNight, HollowsEve ]
authors: [ Racci ]
description: Core lib for my plugins
website: https://github.com/DaRacci/RacciCore/
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2-native-mt
  - org.apache.commons:commons-lang3:3.12.0
  - org.apache.commons:commons-text:1.9
  - org.apache.commons:commons-collections4:4.4
  - net.kyori:adventure-platform-bukkit:4.0.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0
