name: RacciLib
version: '${version}'
main: me.racci.raccilib.RacciLib
api-version: 1.17
load: STARTUP
loadbefore: [ Sylphia ]
authors: [ Racci ]
description: Core lib for my plugins
website: https://github.com/DaRacci/RacciLib/
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2-native-mt
  - org.apache.commons:commons-lang3:3.12.0
  - org.apache.commons:commons-text:1.9
  - org.apache.commons:commons-collections4:4.4
