name: RacciCore
version: '${version}'
main: me.racci.raccicore.RacciCore
api-version: 1.17
load: STARTUP
loadbefore: [ Sylphia, Sylph, BloodNight, HollowsEve ]
authors: [ Racci ]
description: Core lib for my plugins
website: https://github.com/DaRacci/RacciLib/

libraries:
  - ${kotlinstdlib}
  - ${kotlinreflect}
  - ${kotlinXcoroutinesCore}
  - ${kotlinXcoroutinesJvm}
  - ${kotlinXserializationJson}
  - ${kotlinXdateTime}
  - ${commonslang3}
  - ${commonscollections4}
  - ${commonstext}
  - ${mcCoroutineCore}
  - ${mcCoroutineAPI}
