name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Minix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup build cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --info

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Minix-${{ steps.vars.outputs.sha_short }}
          path: |
            build/libs/Minix-*.jar
            Minix-Core/build/libs/**
            Minix-API/build/libs/**

  docs:
    name: Build and upload docs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build docs
        run: ./gradlew dokkaHtmlMulitModule --info

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs_changed:
              - 'docs/**'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: steps.filter.outputs.docs_changed == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true
          full_commit_message: Publish documentation

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish to repo
        run: ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}

      - name: Create changelog
        uses: orhun/git-cliff-action@v1.1.6
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md

      - name: Set release body
        id: release
        shell: base
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=RELEASE_BODY::$r"

      - name: Upload release
        uses: svenstaro/upload-release-action@latest
        with:
          file: build/libs/**
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: ${{ steps.release.outputs.RELEASE_BODY }}
