name: Java CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Minix
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup build cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --info

      - name: Get version from gradle
        shell: bash
        id: extract_version
        run: |
          version=`./gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}'`
          echo "::set-output name=version::$version"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Minix-${{ steps.extract_version.outputs.version }}
          path: |
            build/libs/Minix-${{ steps.extract_version.outputs.version }}.jar
            **/build/libs/Minix-*-*-sources.jar

  docs:
    name: Build and upload docs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build docs
        run: ./gradlew dokkaHtmlMultiModule --info

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/
          keep_files: true
          full_commit_message: Publish documentation

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Publish to repo
        run: ./gradlew publish -PRacciRepoUsername=${{ secrets.REPO_PUBLISH_USERNAME }} -PRacciRepoPassword=${{ secrets.REPO_PUBLISH_PASSWORD }}

      - name: Create changelog
        uses: orhun/git-cliff-action@v1.1.6
        with:
          config: cliff.toml
          args: -vv --latest --strip header --strip footer
        env:
          OUTPUT: CHANGELOG.md

      - name: Set release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=RELEASE_BODY::$r"

      - name: Upload release
        uses: svenstaro/upload-release-action@latest
        with:
          file: build/libs/**
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.version }}
          body: ${{ steps.release.outputs.RELEASE_BODY }}
