name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Setup build cache
        uses: gradle/gradle-build-action@v2

      - id: version
        run: |
          version='CI-${{ github.run_number }}'
          echo "::set-output name=version::$version"

      - name: Build
        run: ./gradlew build -Pversion=${{ steps.version.outputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: Minix-${{ steps.version.outputs.version }}
          path: |
            build/libs/Minix-${{ steps.version.outputs.version }}.jar
            **/build/libs/Minix-*-*-sources.jar
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew clean test