name: Java CI

on: [push]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[SKIP]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup build cache
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/jdks
            ~/.gradle/native
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: RacciCore-DEV-${{ steps.vars.outputs.sha_short }}
          path: build/libs