name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, edited ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - id: version
        run: |
          version='CI-${{ github.run_number }}'
          echo "::set-output name=version::$version"

      - name: Build
        run: ./gradlew build -Pversion=${{ steps.version.outputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Minix-${{ steps.version.outputs.version }}
          path: |
            build/libs/Minix-${{ steps.version.outputs.version }}.jar
            **/build/libs/Minix-*-*-sources.jar
          if-no-files-found: error

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Test
        run: ./gradlew clean test

  sentry:
    name: Sentry
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: contains(needs.build.outputs.version, 'SNAPSHOT')
          if_true: "development"
          if_false: "production"

      - name: Sentry Release
        uses: getsentry/action-release@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          version: ${{ needs.build.outputs.version }}
          environment: ${{ steps.condval.outputs.value }}
          finalize: ${{ needs.build.outputs.version.contains('SNAPSHOT') && 'false' || 'true' }}
