name: Build RacciCore
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Build with Gradle
      run: ./gradlew build
    - run: mkdir staging && cp build/libs/*.jar staging
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
